services:
  - type: web
    name: cashazo-backend
    env: node
    region: oregon
    plan: free
    
    buildCommand: bash render-build.sh
    startCommand: npm start
    
    branches:
      - branch: main
        autoPublish: true
    
    healthCheckPath: /health
    healthCheckInterval: 30
    healthCheckTimeout: 10
